server:
  port: 9003
spring:
  application:
    name: springcloud-sentinel-provider-dept
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        #bus刷新端点是/bus-refresh
        include: "*"
