 server:
   port: 53020

 spring:
   application:
     name: uaa-service
   cloud:
     nacos:
       discovery:
         server-addr: localhost:8848
   datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/user_db?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8
     username: root
     password: 123456

 mybatis:
   mapper-locations: classpath:mybatis/mapper/*.xml
   type-aliases-package: com.lyffin.security.distributed.uaa.model
   config-location: classpath:mybatis/mybatis-config.xml

 management:
   endpoints:
     web:
       exposure:
         #bus刷新端点是/bus-refresh
         include: "*"