server:
  port: 8006

#mybatis配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.lyffin.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml

#spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb2?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

#eureka配置
eureka:
  client:
    service-url:
      #单机: defaultZone: http://localhost:7001/eureka/
      #集群
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    #是否将将自己注册进Eureka,默认为true
    register-with-eureka: true
    #是否从eureka抓取注册信息，默认为true，单结点无所谓，集群必须设置true才 能配合ribbon使用负载均衡
    fetch-registry: true
  instance:
    #修改eureka页面上的默认描述信息
    instance-id: springcloud-provider-dept8006
    #设置当前实例的主机名称，否则会是计算机名
    hostname: localhost
    #客户端向服务端发送心跳的时间间隔，单位为秒，默认30秒
    #lease-renewal-interval-in-seconds: 1
    #优先使用ip注册,访问显示ip
    #prefer-ip-address: true

#info配置，配合actuator依赖
info:
  app.name: lyffin_springcloud
  company.name: www.lyffin.com
  build.artifactId: com.lyffin.springcloud
  build.version: 1.0-SNAPSHOT
#springboot2.7.5中，actuator的info端点和info变量是默认不启用的，因此需要手动开启
#开启所有端点，即页面的/info可以访问
management:
  endpoints:
    web:
      exposure:
        include: "*"
  #开启info开头的变量
  info:
    env:
      enabled: true
