server:
  port: 9527
spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true              #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: provider-routh                          #路由id，要求唯一，建议配合服务名
          #uri: http://localhost:8001                 #匹配后提供服务的路由地址
          uri: lb://springcloud-provider-dept         #动态配置路由
          predicates:
          - Path=/dept/get/**                         #断言，路径相匹配的进行路由
          #断言，在这个时间期间才生效
          #- Between=2022-12-20T21:57:39.920+08:00[Asia/Shanghai],2022-12-20T22:57:39.920+08:00[Asia/Shanghai]
          #断言，需要两个参数，cookie name和正则表达式，根据name和表达式去匹配，要求cookie中有username的参数且值为zzyy
          #- Cookie=username,zzyy  #用curl命令测试，curl http://localhost:9527/dept/get/1 --cookie "username=zzyy"
          #断言，参数为属性名称和正则表达式，根据属性值和正则表达式匹配，请求头需要含有X-Request-Id的属性并且值为整数
          #- Header=X-Request-Id, \d+   #curl http://localhost:9527/dept/get/1 -H "X-Request-Id:123" --cookie "username=zzyy"
          #- Host=**.lyffin.com #curl http://localhostL9527/dept/get/1 -H "Host:www.lyffin.com"
          #- Method=GET   #curl -X GET http://localhost9527/dept/get/1
          #- Query=username, \d+ #要有参数名username且值为正整数，curl http://localhost:9527/dept/get/1?username=1
          #其他断言用法在官网有案例
          #filters:          #官网有案例
            #- AddRequestHeader=X-Request-Red, Blue-{segment} #单一过滤器

        - id: provider-routh2                         #路由id，要求唯一，建议配合服务名
           #uri: http://localhost:8001                 #匹配后提供服务的路由地址
          uri: lb://springcloud-provider-dept
          predicates:
            - Path=/dept/list



eureka:
  client:
    service-url:
      #单机: defaultZone: http://localhost:7001/eureka/
      #集群
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
    #是否将将自己注册进Eureka,默认为true
    register-with-eureka: true
    #是否从eureka抓取注册信息，默认为true，单结点无所谓，集群必须设置true才能配合ribbon使用负载均衡
    fetch-registry: true
  instance:
    #修改eureka页面上的默认描述信息
    instance-id: springcloud-gateway-9527
    #设置当前实例的主机名称，否则会是计算机名
    hostname: localhost
    #客户端向服务端发送心跳的时间间隔，单位为秒，默认30秒
    #lease-renewal-interval-in-seconds: 1
    #优先使用ip注册,访问显示ip
    #prefer-ip-address: true

#info配置，配合actuator依赖
info:
  app.name: lyffin_springcloud
  company.name: www.lyffin.com
  build.artifactId: com.lyffin.springcloud-gateway
  build.version: 1.0-SNAPSHOT
#springboot2.7.5中，actuator的info端点和info变量是默认不启用的，因此需要手动开启
#开启所有端点，即页面的/info可以访问
management:
  endpoints:
    web:
      exposure:
        include: "*"
  #开启info开头的变量
  info:
    env:
      enabled: true
