server:
  port: 9003
spring:
  application:
    name: springcloud-alibaba-consumer-dept
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#切换nacos支持的模式，支持AP和CP
# curl -X PUT localhost:8848/nacos/v1/ns/operator/switches?entry=serverMode&value=CP

#消费者访问的微服务名名称
service-url:
  nacos-user-service: http://springcloud-alibaba-provider-dept
