server:
  port: 3344

spring:
  application:
    name: springcloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:lyffin1997/springcloud-config.git
          #搜索目录,仓库名
          search-paths:
            - springcloud-config
      #读取分支
      label: master

#rabbitMQ相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      #单机: defaultZone: http://localhost:7001/eureka/
      #集群
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
    #是否将将自己注册进Eureka,默认为true
    register-with-eureka: true
    #是否从eureka抓取注册信息，默认为true，单结点无所谓，集群必须设置true才能配合ribbon使用负载均衡
    fetch-registry: true
  instance:
    #修改eureka页面上的默认描述信息
    instance-id: springcloud-config-center-3344
    #设置当前实例的主机名称，否则会是计算机名
    hostname: localhost
    #客户端向服务端发送心跳的时间间隔，单位为秒，默认30秒
    #lease-renewal-interval-in-seconds: 1
    #优先使用ip注册,访问显示ip
    #prefer-ip-address: true

#info配置，配合actuator依赖
info:
  app.name: lyffin_springcloud
  company.name: www.lyffin.com
  build.artifactId: com.lyffin.springcloud-config-center
  build.version: 1.0-SNAPSHOT
#springboot2.7.5中，actuator的info端点和info变量是默认不启用的，因此需要手动开启
#开启所有端点，即页面的/info可以访问
management:
  endpoints:
    web:
      exposure:
        #bus刷新端点是/bus-refresh
        include: "*"
  #开启info开头的变量
  info:
    env:
      enabled: true