server:
  port: 8004

#spring配置
spring:
  application:
    name: springcloud-consumer-dept

#eureka配置
eureka:
  client:
    service-url:
      #单机: defaultZone: http://localhost:7001/eureka/
      #集群
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
    #是否将将自己注册进Eureka,默认为true
    register-with-eureka: true
    #是否从eureka抓取注册信息，默认为true，单结点无所谓，集群必须设置true才能配合ribbon使用负载均衡
    fetch-registry: true
  instance:
    #修改eureka页面上的默认描述信息
    instance-id: springcloud-consumer-8004
    #设置当前实例的主机名称，否则会是计算机名
    hostname: localhost
    #客户端向服务端发送心跳的时间间隔，单位为秒，默认30秒
    #lease-renewal-interval-in-seconds: 1
    #优先使用ip注册,访问显示ip
    #prefer-ip-address: true