server:
  port: 84
spring:
  application:
    name: springcloud-sentinel-consumer-dept
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8858
        #sentinel后台通信端口，默认8719，若被占用会往后扫描
        port: 8719
      web-context-unify: false  #默认为true，若不设为false，链路限流不生效，配合配置文件和@SentinelResource注解
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: springcloud-sentinel-consumer-dept
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
#nacos上配置
#  [
#  {
#    "resource": "/rateLimit/byUrl",      资源名称
#    "limitApp": "default",               来源应用
#    "grade": 1,                          阈值类型，0线程数，1QPS
#    "count": 1,                          单机阈值
#    "strategy": 0,                       流控模式，0表示直接，1表示关联，2表示链路
#    "controlBehavior": 0,                流控效果，0表示快速失败，1表示warm up，2表示排队等待
#    "clusterMode": false
#  }
#  ]


#actuator相关
#springboot2.7.5中，actuator的info端点和info变量是默认不启用的，因此需要手动开启
#开启所有端点，即页面的/info可以访问
management:
  endpoints:
    web:
      exposure:
        #bus刷新端点是/bus-refresh
        include: "*"

service-url:
  nacos-user-service: http://springcloud-sentinel-provider-dept
#激活sentinel对feign对支持,不加这个openfeign的fallback降级无法使用
feign:
  sentinel:
    enabled: true
