server:
  port: 9002

spring:
  application:
    name: springcloud-alibaba-provider-dept
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848
        #nginx地址
        server-addr: localhost:80 
        group: TEST_GROUP
        namespace: cd6bad40-3558-4178-9593-2fe3655b9acd

#actuator相关
#info配置，配合actuator依赖
info:
  app.name: lyffin_springcloud
  company.name: www.lyffin.com
  build.artifactId: com.lyffin.springcloud-alibaba-nacos
  build.version: 1.0-SNAPSHOT
#springboot2.7.5中，actuator的info端点和info变量是默认不启用的，因此需要手动开启
#开启所有端点，即页面的/info可以访问
management:
  endpoints:
    web:
      exposure:
        #bus刷新端点是/bus-refresh
        include: "*"
  #开启info开头的变量
  info:
    env:
      enabled: true